name: Despliegue de Esbilla API (Artifact Registry) ğŸš€

on:
  push:
    branches: [ main ]
    paths: [ 'esbilla-api/**' ]

env:
  REGION: europe-4
  PROJECT_ID: esbilla-cmp # Puees ponelo direutu equÃ­ o usalu como secret
  REPO_NAME: esbilla-docker
  IMAGE_NAME: esbilla-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar cÃ³digu ğŸ“¥
        uses: actions/checkout@v4

      - name: Autenticar en Google Cloud ğŸ”‘
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configurar Google Cloud SDK ğŸŸ¢
        uses: google-github-actions/setup-gcloud@v2

      - name: Configurar Docker pa Artifact Registry ğŸ‹
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Construyir y Xubir Imaxe ğŸ—ï¸
        run: |
          # El tag completu de la imaxe
          TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          # Entramos nel direutoriu y construyimos
          docker build -t $TAG ./esbilla-api
          docker push $TAG

      - name: Desplegar en Cloud Run â˜ï¸
        run: |
          TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          gcloud run deploy esbilla-api \
            --image $TAG \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID }}